apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  creationTimestamp: null
  name: namespaceteamlabel01
spec:
  crd:
    spec:
      names:
        kind: NamespaceTeamLabel01
  targets:
  - rego: |-
      package namespace_team_label_01

      violation[{"msg": msg, "details": {}}] {
        resource := input.review.object

        not resource.metadata.labels.team

        msg := sprintf("%s: Namespace does not have a required 'team' label", [resource.metadata.name])
      }
    target: admission.k8s.gatekeeper.sh
status: {}
