#!/bin/sh

set -eux

: "${MANIFESTS_OUTPUT_DIR:?Need to set MANIFESTS_OUTPUT_DIR}"

rm -rf "${MANIFESTS_OUTPUT_DIR}"
mkdir -p "${MANIFESTS_OUTPUT_DIR}"

HELM_VERSION="3.6.3"
HELM_IMAGE="alpine/helm:${HELM_VERSION}"


# template gatekeeper chart manifests
GATEKEEPER_HELM_CHART_REPO="https://open-policy-agent.github.io/gatekeeper/charts"
GATEKEEPER_HELM_CHART_VERSION="3.5.2"
GATEKEEPER_HELM_CHART_DIR_NAME="gatekeeper"
GATEKEEPER_HELM_CHART_DIR="/tmp/${GATEKEEPER_HELM_CHART_DIR_NAME}"
GATEKEEPER_HELM_CHART_NAME="gatekeeper"
GATEKEEPER_OUTPUT_MANIFEST="${MANIFESTS_OUTPUT_DIR}/${GATEKEEPER_HELM_CHART_NAME}.yml"

rm -rf "${GATEKEEPER_HELM_CHART_DIR}"

docker run -it --rm -v /tmp:/apps -w /apps "${HELM_IMAGE}" \
    pull --repo "${GATEKEEPER_HELM_CHART_REPO}" --version "${GATEKEEPER_HELM_CHART_VERSION}" \
    --untardir "${GATEKEEPER_HELM_CHART_DIR_NAME}" --untar "${GATEKEEPER_HELM_CHART_NAME}"

manifest_content=$(docker run -it --rm -v /tmp:/apps -w /apps/ "${HELM_IMAGE}" \
    template --include-crds --set replicas=1 --set auditInterval=10 --namespace gatekeeper-system \
    "${GATEKEEPER_HELM_CHART_NAME}" "${GATEKEEPER_HELM_CHART_DIR_NAME}/${GATEKEEPER_HELM_CHART_NAME}")

echo "${manifest_content}" > "${GATEKEEPER_OUTPUT_MANIFEST}"


# template gatekeeper-policy-manager manifests
GATEKEEPER_POLICY_MANAGER_RAW_URL="https://raw.githubusercontent.com/sighupio/gatekeeper-policy-manager"
GATEKEEPER_POLICY_MANAGER_VERSION="v0.4.2"
GATEKEEPER_POLICY_MANAGER_MANIFESTS_URL="${GATEKEEPER_POLICY_MANAGER_RAW_URL}/${GATEKEEPER_POLICY_MANAGER_VERSION}/manifests"
GATEKEEPER_POLICY_MANAGER_NAME="gatekeeper-policy-manager"
GATEKEEPER_POLICY_MANAGER_DIR="/tmp/${GATEKEEPER_POLICY_MANAGER_NAME}"
GATEKEEPER_POLICY_MANAGER_OUTPUT_MANIFEST="${MANIFESTS_OUTPUT_DIR}/${GATEKEEPER_POLICY_MANAGER_NAME}.yml"

rm -rf "${GATEKEEPER_POLICY_MANAGER_DIR}"
mkdir -p "${GATEKEEPER_POLICY_MANAGER_DIR}"

curl -sL "${GATEKEEPER_POLICY_MANAGER_MANIFESTS_URL}/rbac.yaml" >> "${GATEKEEPER_POLICY_MANAGER_OUTPUT_MANIFEST}"
echo "---" >> "${GATEKEEPER_POLICY_MANAGER_OUTPUT_MANIFEST}"
curl -sL "${GATEKEEPER_POLICY_MANAGER_MANIFESTS_URL}/deployment.yaml" | sed "s/quay.io\/sighup\/gatekeeper-policy-manager/quay.io\/sighup\/gatekeeper-policy-manager:${GATEKEEPER_POLICY_MANAGER_VERSION}/" >> "${GATEKEEPER_POLICY_MANAGER_OUTPUT_MANIFEST}"
echo "---" >> "${GATEKEEPER_POLICY_MANAGER_OUTPUT_MANIFEST}"
curl -sL "${GATEKEEPER_POLICY_MANAGER_MANIFESTS_URL}/service.yaml" >> "${GATEKEEPER_POLICY_MANAGER_OUTPUT_MANIFEST}"
